export const currencies = [
  { code: "AED", country: "AE", name: "UAE Dirham" },
  { code: "AFN", country: "AF", name: "Afghan Afghani" },
  { code: "ALL", country: "AL", name: "Albanian Lek" },
  { code: "AMD", country: "AM", name: "Armenian Dram" },
  { code: "ANG", country: "NL", name: "Netherlands Antillean Guilder" },
  { code: "AOA", country: "AO", name: "Angolan Kwanza" },
  { code: "ARS", country: "AR", name: "Argentine Peso" },
  { code: "AUD", country: "AU", name: "Australian Dollar" },
  { code: "AWG", country: "AW", name: "Aruban Florin" },
  { code: "AZN", country: "AZ", name: "Azerbaijani Manat" },
  { code: "BAM", country: "BA", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "BBD", country: "BB", name: "Barbadian Dollar" },
  { code: "BDT", country: "BD", name: "Bangladeshi Taka" },
  { code: "BGN", country: "BG", name: "Bulgarian Lev" },
  { code: "BHD", country: "BH", name: "Bahraini Dinar" },
  { code: "BIF", country: "BI", name: "Burundian Franc" },
  { code: "BMD", country: "BM", name: "Bermudan Dollar" },
  { code: "BND", country: "BN", name: "Brunei Dollar" },
  { code: "BOB", country: "BO", name: "Bolivian Boliviano" },
  { code: "BRL", country: "BR", name: "Brazilian Real" },
  { code: "BSD", country: "BS", name: "Bahamian Dollar" },
  { code: "BTN", country: "BT", name: "Bhutanese Ngultrum" },
  { code: "BWP", country: "BW", name: "Botswanan Pula" },
  { code: "BYN", country: "BY", name: "Belarusian Ruble" },
  { code: "BZD", country: "BZ", name: "Belize Dollar" },
  { code: "CAD", country: "CA", name: "Canadian Dollar" },
  { code: "CDF", country: "CD", name: "Congolese Franc" },
  { code: "CHF", country: "CH", name: "Swiss Franc" },
  { code: "CLP", country: "CL", name: "Chilean Peso" },
  { code: "CNY", country: "CN", name: "Chinese Yuan" },
  { code: "COP", country: "CO", name: "Colombian Peso" },
  { code: "CRC", country: "CR", name: "Costa Rican Colon" },
  { code: "CUP", country: "CU", name: "Cuban Peso" },
  { code: "CVE", country: "CV", name: "Cape Verdean Escudo" },
  { code: "CZK", country: "CZ", name: "Czech Koruna" },
  { code: "DJF", country: "DJ", name: "Djiboutian Franc" },
  { code: "DKK", country: "DK", name: "Danish Krone" },
  { code: "DOP", country: "DO", name: "Dominican Peso" },
  { code: "DZD", country: "DZ", name: "Algerian Dinar" },
  { code: "EGP", country: "EG", name: "Egyptian Pound" },
  { code: "ERN", country: "ER", name: "Eritrean Nakfa" },
  { code: "ETB", country: "ET", name: "Ethiopian Birr" },
  { code: "EUR", country: "EU", name: "Euro" },
  { code: "FJD", country: "FJ", name: "Fijian Dollar" },
  { code: "FKP", country: "FK", name: "Falkland Islands Pound" },
  { code: "GBP", country: "GB", name: "British Pound" },
  { code: "GEL", country: "GE", name: "Georgian Lari" },
  { code: "GHS", country: "GH", name: "Ghanaian Cedi" },
  { code: "GIP", country: "GI", name: "Gibraltar Pound" },
  { code: "GMD", country: "GM", name: "Gambian Dalasi" },
  { code: "GNF", country: "GN", name: "Guinean Franc" },
  { code: "GTQ", country: "GT", name: "Guatemalan Quetzal" },
  { code: "GYD", country: "GY", name: "Guyanaese Dollar" },
  { code: "HKD", country: "HK", name: "Hong Kong Dollar" },
  { code: "HNL", country: "HN", name: "Honduran Lempira" },
  { code: "HRK", country: "HR", name: "Croatian Kuna" },
  { code: "HTG", country: "HT", name: "Haitian Gourde" },
  { code: "HUF", country: "HU", name: "Hungarian Forint" },
  { code: "IDR", country: "ID", name: "Indonesian Rupiah" },
  { code: "ILS", country: "IL", name: "Israeli Shekel" },
  { code: "INR", country: "IN", name: "Indian Rupee" },
  { code: "IQD", country: "IQ", name: "Iraqi Dinar" },
  { code: "IRR", country: "IR", name: "Iranian Rial" },
  { code: "ISK", country: "IS", name: "Icelandic Krona" },
  { code: "JMD", country: "JM", name: "Jamaican Dollar" },
  { code: "JOD", country: "JO", name: "Jordanian Dinar" },
  { code: "JPY", country: "JP", name: "Japanese Yen" },
  { code: "KES", country: "KE", name: "Kenyan Shilling" },
  { code: "KGS", country: "KG", name: "Kyrgystani Som" },
  { code: "KHR", country: "KH", name: "Cambodian Riel" },
  { code: "KMF", country: "KM", name: "Comorian Franc" },
  { code: "KPW", country: "KP", name: "North Korean Won" },
  { code: "KRW", country: "KR", name: "South Korean Won" },
  { code: "KWD", country: "KW", name: "Kuwaiti Dinar" },
  { code: "KYD", country: "KY", name: "Cayman Islands Dollar" },
  { code: "KZT", country: "KZ", name: "Kazakhstani Tenge" },
  { code: "LAK", country: "LA", name: "Laotian Kip" },
  { code: "LBP", country: "LB", name: "Lebanese Pound" },
  { code: "LKR", country: "LK", name: "Sri Lankan Rupee" },
  { code: "LRD", country: "LR", name: "Liberian Dollar" },
  { code: "LSL", country: "LS", name: "Lesotho Loti" },
  { code: "LYD", country: "LY", name: "Libyan Dinar" },
  { code: "MAD", country: "MA", name: "Moroccan Dirham" },
  { code: "MDL", country: "MD", name: "Moldovan Leu" },
  { code: "MGA", country: "MG", name: "Malagasy Ariary" },
  { code: "MKD", country: "MK", name: "Macedonian Denar" },
  { code: "MMK", country: "MM", name: "Myanmar Kyat" },
  { code: "MNT", country: "MN", name: "Mongolian Tugrik" },
  { code: "MOP", country: "MO", name: "Macanese Pataca" },
  { code: "MRU", country: "MR", name: "Mauritanian Ouguiya" },
  { code: "MUR", country: "MU", name: "Mauritian Rupee" },
  { code: "MVR", country: "MV", name: "Maldivian Rufiyaa" },
  { code: "MWK", country: "MW", name: "Malawian Kwacha" },
  { code: "MXN", country: "MX", name: "Mexican Peso" },
  { code: "MYR", country: "MY", name: "Malaysian Ringgit" },
  { code: "MZN", country: "MZ", name: "Mozambican Metical" },
  { code: "NAD", country: "NA", name: "Namibian Dollar" },
  { code: "NGN", country: "NG", name: "Nigerian Naira" },
  { code: "NIO", country: "NI", name: "Nicaraguan Cordoba" },
  { code: "NOK", country: "NO", name: "Norwegian Krone" },
  { code: "NPR", country: "NP", name: "Nepalese Rupee" },
  { code: "NZD", country: "NZ", name: "New Zealand Dollar" },
  { code: "OMR", country: "OM", name: "Omani Rial" },
  { code: "PAB", country: "PA", name: "Panamanian Balboa" },
  { code: "PEN", country: "PE", name: "Peruvian Sol" },
  { code: "PGK", country: "PG", name: "Papua New Guinean Kina" },
  { code: "PHP", country: "PH", name: "Philippine Peso" },
  { code: "PKR", country: "PK", name: "Pakistani Rupee" },
  { code: "PLN", country: "PL", name: "Polish Zloty" },
  { code: "PYG", country: "PY", name: "Paraguayan Guarani" },
  { code: "QAR", country: "QA", name: "Qatari Rial" },
  { code: "RON", country: "RO", name: "Romanian Leu" },
  { code: "RSD", country: "RS", name: "Serbian Dinar" },
  { code: "RUB", country: "RU", name: "Russian Ruble" },
  { code: "RWF", country: "RW", name: "Rwandan Franc" },
  { code: "SAR", country: "SA", name: "Saudi Riyal" },
  { code: "SBD", country: "SB", name: "Solomon Islands Dollar" },
  { code: "SCR", country: "SC", name: "Seychellois Rupee" },
  { code: "SDG", country: "SD", name: "Sudanese Pound" },
  { code: "SEK", country: "SE", name: "Swedish Krona" },
  { code: "SGD", country: "SG", name: "Singapore Dollar" },
  { code: "SHP", country: "SH", name: "St. Helena Pound" },
  { code: "SLL", country: "SL", name: "Sierra Leonean Leone" },
  { code: "SOS", country: "SO", name: "Somali Shilling" },
  { code: "SRD", country: "SR", name: "Surinamese Dollar" },
  { code: "STN", country: "ST", name: "São Tomé & Príncipe Dobra" },
  { code: "SVC", country: "SV", name: "Salvadoran Colon" },
  { code: "SYP", country: "SY", name: "Syrian Pound" },
  { code: "SZL", country: "SZ", name: "Swazi Lilangeni" },
  { code: "THB", country: "TH", name: "Thai Baht" },
  { code: "TJS", country: "TJ", name: "Tajikistani Somoni" },
  { code: "TMT", country: "TM", name: "Turkmenistani Manat" },
  { code: "TND", country: "TN", name: "Tunisian Dinar" },
  { code: "TOP", country: "TO", name: "Tongan Paʻanga" },
  { code: "TRY", country: "TR", name: "Turkish Lira" },
  { code: "TTD", country: "TT", name: "Trinidad & Tobago Dollar" },
  { code: "TWD", country: "TW", name: "Taiwan Dollar" },
  { code: "TZS", country: "TZ", name: "Tanzanian Shilling" },
  { code: "UAH", country: "UA", name: "Ukrainian Hryvnia" },
  { code: "UGX", country: "UG", name: "Ugandan Shilling" },
  { code: "USD", country: "US", name: "US Dollar" },
  { code: "UYU", country: "UY", name: "Uruguayan Peso" },
  { code: "UZS", country: "UZ", name: "Uzbekistani Som" },
  { code: "VES", country: "VE", name: "Venezuelan Bolívar" },
  { code: "VND", country: "VN", name: "Vietnamese Dong" },
  { code: "VUV", country: "VU", name: "Vanuatu Vatu" },
  { code: "WST", country: "WS", name: "Samoan Tala" },
  { code: "XAF", country: "CM", name: "Central African CFA Franc" },
  { code: "XCD", country: "AG", name: "East Caribbean Dollar" },
  { code: "XOF", country: "SN", name: "West African CFA Franc" },
  { code: "XPF", country: "PF", name: "CFP Franc" },
  { code: "YER", country: "YE", name: "Yemeni Rial" },
  { code: "ZAR", country: "ZA", name: "South African Rand" },
  { code: "ZMW", country: "ZM", name: "Zambian Kwacha" },
  { code: "ZWL", country: "ZW", name: "Zimbabwean Dollar" },
]